### ISSUE TITLE
身份验证

### ISSUE THREAD

**Issue by bohesocool** [bincooo/SillyTavern-Docker#1]
你好，我想问一下，身份验证的账号密码是什么呢

**Comment by bincooo** [comment]
抱歉，没留意到你的issue。
<img width="1104" alt="Screenshot 2024-07-14 at 05 03 40" src="https://github.com/user-attachments/assets/40a24f38-20b5-48a1-bfca-1058322699ee">

在私有的环境变量中添加username和password的值即可。

**Comment by bohesocool** [comment]
好的好的，谢谢，我之前也看见了
